### ISSUE TITLE
Liroth Saplings Crashing on Growth

### ISSUE THREAD

**Issue by Matikpl1689** [decodinatorX/Liroth-Revamped-Fabric#11]
When any of the saplings from the mod grow up the game crashes heres the crash log

Time: 2022-09-16 13:24:14
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at com.decodinator.liroth.core.world.trees.DamnationTree.method_11430(DamnationTree.java:15)
	at net.minecraft.class_2647.method_11431(class_2647.java:21)
	at net.minecraft.class_2473.method_10507(class_2473.java:48)
	at net.minecraft.class_2473.method_9652(class_2473.java:64)
	at net.minecraft.class_1752.method_7720(class_1752.java:74)
	at net.minecraft.class_1752.method_7884(class_1752.java:43)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_3225.method_14262(class_3225.java:355)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:worldgen/configured_feature / minecraft:liroth])
	at net.minecraft.class_2370.method_40274(class_2370.java:81)
	at net.minecraft.class_2370.method_31051(class_2370.java:91)
	at net.minecraft.class_2370.method_10273(class_2370.java:87)
	at net.fabricmc.fabric.impl.registry.sync.DynamicRegistrySync.lambda$setupSync$1(DynamicRegistrySync.java:63)
	at net.minecraft.class_2370.mdb4b5b3$lambda$new$0$5(class_2370.java:1105)
	at net.minecraft.class_2370.handler$bli000$setPost(class_2370.java:1206)
	at net.minecraft.class_2370.method_31051(class_2370.java:130)
	at net.minecraft.class_2370.method_10273(class_2370.java:87)
	at net.minecraft.class_2370.method_10272(class_2370.java:135)
	at net.minecraft.class_5458.method_39203(class_5458.java:135)
	at net.minecraft.class_5458.method_30562(class_5458.java:131)
	at net.minecraft.class_5458.method_40360(class_5458.java:122)
	at net.minecraft.class_6803.method_39708(class_6803.java:75)
	at com.decodinator.liroth.core.LirothConfiguredFeatures.<clinit>(LirothConfiguredFeatures.java:53)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18.0.1.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1932954664 bytes (1843 MiB) / 4697620480 bytes (4480 MiB) up to 6392119296 bytes (6096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Phenom(tm) II X4 965 Processor
	Identifier: AuthenticAMD Family 16 Model 4 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.41
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 660
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x11c0
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6589
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: Unknown
	Virtual memory max (MB): 16381.55
	Virtual memory used (MB): 10744.39
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 1494.01
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms396m -Xmx6095m
	Fabric Mods: 
		architectury: Architectury 6.2.46
		awesomedungeonnether: Awesome dungeon nether 3.0.0
		bclib: BCLib 2.1.0
		betterend: Better End 2.1.0
		betterlily: Better Lily Pads 1.1.0
		betternether: Better Nether 7.1.0
		bettersculksensor: BetterSculkSensor 1.1.8
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.55
			fiber: fiber 0.23.0-2
		cotw: Curse Of The Warden 1.0.0
		creaturesofthesnow: Creatures Of The Snow 3.0.0+1.19.2
		cullleaves: Cull Leaves 2.3.4
		cyclepaintings-fabric: Cycle Paintings (Fabric) 2.6
		delightful-froge: Delightful Froge 0.1.0+1.19
		doom: Doom Fabric 4.2.15
		earthtojavamobs: Earth2Java 1.9.3
		echoingdepths: Echoing Descent 1.0.0-1.19.2
		ecologics: Ecologics 2.1.10
		edenring: EdenRing 0.6.4
		effective: Effective 1.3
		fabric-api: Fabric API 0.61.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.0+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.9+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.31+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.29+4e8ca3fd90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.25+726b652090
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.0+1cc24b1b90
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.0+8f88597390
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		forgeconfigapiport: Forge Config API Port 4.2.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		friendsandfoes: Friends&Foes 1.5.10
			com_github_llamalad7_mixinextras: MixinExtras 0.0.12
		fwaystones: Fabric Waystones 3.0.3+mc1.19.2
			pinlib: PinLib 0.1.3+1.19
		geckolib3: Geckolib 3.1.20
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		hedgehog: Hedgehog 1.19-1.2.0
		identity: Identity 2.6.0-1.19.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		java: Java HotSpot(TM) 64-Bit Server VM 18
		jei: Just Enough Items 11.3.0.262
		libraryferret: Library ferret 3.0.0
		liroth: Liroth 1.0.2
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
		lithium: Lithium 0.8.3
		midnightlib: MidnightLib 0.6.0
		minecraft: Minecraft 1.19.2
		mob_catcher: Mob Catcher 1.2.9
		mobbattle: Mob Battle Mod 1.19-2.4.3.1
		mobhealthbar: MobHealthBar 2.1.0
		modmenu: Mod Menu 4.0.6
		moremcmeta: MoreMcmeta 1.19-3.0.5
		mushroom_additions: Mushroom Additions 1.0.0
		nears: Nears 1.2.3
		npcvariety: NPC Variety 2.2.2
		observed: Observed 1.3.3
		origins: Origins 1.7.0
			apoli: Apoli 2.6.0
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		pehkui: Pehkui 3.4.2+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		placeableblazerods-fabric: Placeable Blaze Rods (Fabric) 1.8
		playerabilitylib: Pal 1.6.0
		puzzleslib: Puzzles Lib 4.3.4
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		sculk_worm: Sculk Worm 0.1.6
		sculkhornid: Sculk Horn Mod 1.0.0-1.19.x
		sculksieg: Sculker 1.0.0
		smoke_suppression: Smoke Suppression 1.0.13
			crowdin-translate: CrowdinTranslate 1.4+1.19
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.10+mc1.19.2-build.64
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		strawgolem: Straw Golem 2.0.0b2
		themissingvillages: BigReefer's The Missing Villages Mod 1.0.2
		tinyskeletons: Tiny Skeletons 4.2.1
		totw_additions: Towers of the Wild: Additions 1.2.3
		treeharvester-fabric: Tree Harvester (Fabric) 5.6
		trinkets: Trinkets 3.4.0
		wardenloot: Warden Loot 1.1.2-1.19.x
		wardentools: Warden Tools 1.6.1
		wilderwild: Wilder Wild 1.0.6-Fabric+1.19.2
			mm: Manningham Mills 2.3
	Server Running: true
	Player Count: 1 / 8; [class_3222['Matikpl168'/37, l='ServerLevel[New World]', x=140.80, y=-60.00, z=-311.73]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19.2

Yes i had other mods on however i dont think they caushed it

**Comment by decodinatorX** [comment]
Hi, this bug was fixed in version 1.0.2.1, please update to it. If it is still occurring with the newest update, please update me.
