### ISSUE TITLE
is the grass supposed to be green?

### ISSUE THREAD

**Issue by AnAwesomGuy** [decodinatorX/Liroth-Revamped-Fabric#18]
i thought it was supposed to be purple...
also, i have better biome blending
![image](https://user-images.githubusercontent.com/79700396/224458534-8494a528-1507-460d-856b-5805a17bee21.png)

**Comment by decodinatorX** [comment]
Seems there must be something up with Biome Blending as no the grass is NOT meant to be green, I'll be sure to check it out ASAP.

**Comment by AnAwesomGuy** [comment]
i removed better biome blending and it still happens
idk why

**Comment by decodinatorX** [comment]
Hi, can you please give me a list of your mods?

**Comment by AnAwesomGuy** [comment]
ok
[mods.txt](https://github.com/decodinatorX/Liroth-Revamped-Fabric/files/11046167/mods.txt)

**Comment by decodinatorX** [comment]
Version below 1.19 will no longer be receiving updates, I apologize for the inconvenience.
