### ISSUE TITLE
Crash on startup 1.19.3 - 1.2.3 Fabric 

### ISSUE THREAD

**Issue by Lart-Iste** [decodinatorX/Liroth-Revamped-Fabric#19]
Hi, my game crash on startup with this code of exit 1 (0x1)

To Reproduce
I don't know how to reproduce this, I think its specific with my mod list and one or more conflicts, but where and why .... ^^

Expected behavior
launch the game properly

Screenshots & Logs
https://paste.ee/p/8NF2u

Mod Version :
1.2.3

Additional context
Ask me ^^

**Comment by decodinatorX** [comment]
Could you kindly repost the log and the screenshots, they've since been removed, apologies on the hiatus.

**Comment by decodinatorX** [comment]
Since the request has been unfilled within two weeks of original post and the inability to recreate said circumstances, I am closing this issue until further notice.
