### ISSUE TITLE
Guide Book not working

### ISSUE THREAD

**Issue by doubleaxes** [decodinatorX/Liroth-Revamped-Fabric#24]

**Comment by doubleaxes** [comment]
when I right click the book its not opening (1.20.1) My patchouli version: Patchouli-1.20.1-81-FABRIC

**Comment by kingkuys2123** [comment]
That's prolly because of the new 1.20 patchouli update. The patchouli book resource location have changed from `data` to `assets` folder. This should just be an easy patch. Here's the upgrade guide. @decodinatorX 

https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120/

**Comment by decodinatorX** [comment]
Ah hell, I will see to it Monday, I apologize for not seeing this sooner.

**Comment by kingkuys2123** [comment]
> Ah hell, I will see to it Monday, I apologize for not seeing this sooner.

No worries. take your time! 😄

**Comment by decodinatorX** [comment]
Fixed in dev build.
