### ISSUE TITLE
The Mod Menu dependency

### ISSUE THREAD

**Issue by noncom** [decodinatorX/Liroth-Revamped-Fabric#25]
Adding Liroth automatically adds the Mod Menu mod of version `modmenu-2.0.17.jar` , which is the latest version available on CurseForge, but which is not compatible with `Fabric-0.14.22`.

With this mod I'm getting the client crash: [latest.log](https://github.com/decodinatorX/Liroth-Revamped-Fabric/files/12642853/latest.log)
(it's the `latest.log`, no crash log is generated although the client effectively crashes without even opening the window)

Without this mod I'm getting the client crash: [crash-2023-09-17_15.49.02-client.txt](https://github.com/decodinatorX/Liroth-Revamped-Fabric/files/12642848/crash-2023-09-17_15.49.02-client.txt)

To be able to play I replace it with the newer version `modmenu-4.1.0.jar`, available from Modrinth.

I'm not sure, but since the ModMenu mod is an entirely optional convenience mod for the client, it looks like this mod is included as a necessary dependency for Liroth by mistake.
If that's the case, it would be cool if it would be removed from the dependencies to not create this confusion :)

**Comment by decodinatorX** [comment]
Gotcha fam

**Comment by decodinatorX** [comment]
Fixed in dev build.
