### ISSUE TITLE
Incompatible with Paradise Lost

### ISSUE THREAD

**Issue by Tishbyte** [decodinatorX/Liroth-Revamped-Fabric#5]
Cannot be used with the Paradise Lost mod ([https://www.curseforge.com/minecraft/mc-mods/paradise-lost](https://www.curseforge.com/minecraft/mc-mods/paradise-lost)).

**Comment by decodinatorX** [comment]
This issue has since been fixed in the newest 1.18.2 version it would seem

![2022-09-15_20 57 30](https://user-images.githubusercontent.com/16389833/190534011-499a956f-b7cf-44ab-9658-87698442778a.png)
