### ISSUE TITLE
when i have this mod in 1.18.2  enebled it says safe mode everytime i try to load a world

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [decodinatorX/Liroth-Revamped-Fabric#6]
https://drive.google.com/file/d/1KBORxLxtCrs8irxASVJQlvRy0HAK_Biy/view?usp=sharing

**Comment by decodinatorX** [comment]
Please resend this through a different source than Google Drive, such as PasteBin, or any alternatives to this.

**Comment by decodinatorX** [comment]
For the time being, I am going to close this until further notice as this issue may have been fixed within the new versions.
